// Generated by CoffeeScript 1.9.2
(function() {
  var Foo;

  Foo = (function() {
    var bbb;

    Foo.prototype.aaa = 1;

    bbb = 1;

    Foo.ccc = 1;

    Foo.ddd = 1;

    function Foo() {
      var ooo;
      ooo = 5;
      Object.defineProperties(this, {
        aoa: {
          get: function() {
            return ooo;
          },
          set: function(val) {
            ooo = val;
          }
        },
        bob: {
          get: function() {
            return bbb;
          },
          set: function(val) {
            bbb = val;
          }
        }
      });
    }

    return Foo;

  })();

  module.exports = Foo;

}).call(this);
