// Generated by CoffeeScript 1.9.2
(function() {
  var Foo,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Foo = (function() {
    var bbb, innerA;

    bbb = 'west';

    innerA = {};

    function Foo() {
      this.outerA2 = bind(this.outerA2, this);
      var ooo;
      ooo = 5;
      innerA[this] = function() {
        return ooo;
      };
      Object.defineProperties(this, {
        aoa: {
          get: function() {
            return ooo;
          },
          set: function(val) {
            ooo = val;
          }
        },
        bob: {
          get: function() {
            return bbb;
          },
          set: function(val) {
            bbb = val;
          }
        }
      });
    }

    Foo.prototype.outerA1 = function() {
      return innerA();
    };

    Foo.prototype.outerA2 = function() {
      return innerA();
    };

    return Foo;

  })();

  module.exports = Foo;

}).call(this);
