// Generated by CoffeeScript 1.9.2
(function() {
  var Bar, Foo,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Foo = (function() {
    var mm, nn, oo, pp, qq;

    Foo.aa = -4;

    Foo.vv = -1;

    Foo.ww = 5;

    Foo.xx = 0;

    Foo.yy = 3;

    Foo.zz = -2;

    mm = 'm';

    nn = 'n';

    oo = 'o';

    pp = 'p';

    qq = 'q';

    Foo.t1 = 't';

    Foo.prototype.t2 = 't';

    function Foo() {
      this.log2 = bind(this.log2, this);
      var vv, ww;
      this.a = 4;
      this.b = -2;
      this.d = 1;
      ww = -3;
      vv = 3;
      this.m = mm;
      nn = 1;
      oo = 2;
      this.p = pp;
      this.q = qq;
    }

    Foo.prototype.log1 = function() {
      return console.log((mm || 'no') + " " + (nn || 'no') + " " + (oo || 'no') + " " + (pp || 'no') + " " + (qq || 'no'));
    };

    Foo.prototype.log2 = function() {
      return console.log((mm || 'no') + " " + (nn || 'no') + " " + (oo || 'no') + " " + (pp || 'no') + " " + (qq || 'no'));
    };

    Foo.log3 = function() {
      return console.log((mm || 'no') + " " + (nn || 'no') + " " + (oo || 'no') + " " + (pp || 'no') + " " + (qq || 'no'));
    };

    Foo.log4 = function() {
      return console.log((mm || 'no') + " " + (nn || 'no') + " " + (oo || 'no') + " " + (pp || 'no') + " " + (qq || 'no'));
    };

    return Foo;

  })();

  Bar = (function(superClass) {
    extend(Bar, superClass);

    Bar.cc = 3;

    Bar.xx = 2;

    function Bar() {
      var pp, qq, vv, yy;
      this.b = 1;
      vv = 2;
      pp = -1;
      Bar.__super__.constructor.call(this);
      qq = 3;
      this.a = 3;
      this.c = 0;
      yy = 4;
    }

    return Bar;

  })(Foo);

  exports.Foo = Foo;

  exports.Bar = Bar;

}).call(this);
